project:
  type: website

website:
  title: "John Waczak's Family Recipe Collection"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/john-waczak/recipes
      # - icon: twitter
      #   href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css



