---
title: "Grandma Judy's Cheesecake"
author: "Judy Sperry"
date: "2023-04-09"
categories: [dessert, sweet, cake]
---

# History 

The original recipe comes from Grandam Judy's mother, Grandma Katie-- Grandpa remembers having it for the first time back when he started dating Grandma.

# Ingredients

Graham Cracker Crust:

- $1\frac{1}{4}$ cups graham crackers
- $\frac{3}{4}$ cups sugar
- $1 \frac{1}{4}$ cups melted butter (this is the original amount-- I use $\frac{3}{4}$ cups instead)


Cream Cheese Layer: 

- $1$ lb. cream cheese
- $3$ large eggs
- $\frac{3}{4}$ tsp. vanilla  (I usually just give it a good glug)
- $\frac{1}{2}$ cup sugar


Sour Cream Topping: 

- $1$ pt. sour cream
- $\frac{1}{4}$ cup sugar 
- $1$ tsp. vanilla

# Preparation

Mix together ingredients for craham cracker crust and spread evenly into a $9\times 13$ pan (I use metal baking pan. Glass will probably cook a bit slower). Next mix together ingredients for the cream cheese layer in a bowl using a hand mixer until silky smooth.[^1]

[^1]: NOTE: for best results make sure to let cream cheese and eggs come to room temperature before mixing .Otherwise your mixture can end up lumpy!

Bake for $20$ minutes in an oven pre-heated to $375^\circ$F. Afterwards, remove from oven and lets cool for $15$ minutes while you raise the oven to $450^\circ$F for the final layer.

Mix together the ingredients for the sour cream topping and add to the cooled cheesecake. Bake for 10 minutes and then remove. Let cool on counter for ~1 hr and then refrigerate overnight for best results.
