---
title: "Green Bean Casserole"
author: "John Waczak"
date: "2023-11-09"
categories: [casserole, savory, green beans]
---

# History

This recipe comes from [Bon Apetit](https://www.bonappetit.com/recipe/bas-best-green-bean-casserole).

# Ingredients

- $2$ lbs fresh green beans 
- $2$ tbsp extra virgin olive oil (EVOO)
- $1$ lb crimini (white) mushrooms
- $6$ tbsp butter
- $4$ sprigs thyme (or other herbs of your choice)
- $2$ tbsp all purpose flour
- $1\frac{1}{4}$ cup whole milk 
- $1$ cup heavy cream 
- $4$ cloves garlic
- $\frac{1}{2}$ cup grated parmesean
- $\frac{3}{4}$ cup French's crispy fried onions

# Preparation 

Set oven to $375$ $^\circ F$. Blanch green beans in batches in salted water for 3 minutes. Drain + cool beans and trim ends. In a pan, add EVOO and mushrooms and cook until brown. Reduce heat and add 4 tbsp of butter together with sliced herbs (it may be easier to do this step in two batches depending on your pan). Once finished remove mushrooms to a separate bowl. In the same pan, add remaining 2 tbsp of butter. Once melted, add in 2 tbsp of AP flour and whisk until golden & nutty forming a roux. Slowly begin to add milk, whisking to remove any clumps. Do the same with the cream forming a bechemel. Remove from heat and stir in cheese + garlic + pepper. 

Mix together beans and mushrooms into a $9 \times 13$ baking dish. Drape the bechemel sauce over the top of the casserole. Cover with a sheet of aluminum foil. Bake 25-30 minutes covered until bubbling. Remove the foil and bake again until top is browned. Add a layer of French's onions to the top of the casserole and bake again for 3-5 minutes until the onions are slightly darkened and fragrant.
